name: uat-deployment

on:
  push:
    branches:
      - main

jobs:
  uat-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH into EC2 instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.UAT_EC2_HOST }}
        username: ${{ secrets.UAT_EC2_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /var/www/html/cause-i-client
          sudo git reset --hard
          sudo git checkout main
          sudo git pull
          sudo pnpm install  # Re-install dependencies
          sudo pnpm run build
